# -*- coding: utf-8 -*-
"""TextToImageGeneration_CLEAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKrlIkENytEjyO-MwgxE4HQrGBJdPi47
"""

import nbformat

# Set the path to your notebook
file_path = "/content/TextToImageGeneration.ipynb"

# Load the notebook
with open(file_path, "r", encoding="utf-8") as f:
    nb = nbformat.read(f, as_version=4)

# Remove all 'widgets' metadata to fix GitHub rendering issues
if "widgets" in nb["metadata"]:
    del nb["metadata"]["widgets"]

# Save the cleaned notebook
cleaned_path = "/content/TextToImageGeneration_Clean.ipynb"
with open(cleaned_path, "w", encoding="utf-8") as f:
    nbformat.write(nb, f)

print("✔ Notebook cleaned successfully! Download 'TextToImageGeneration_Clean.ipynb' from the sidebar.")

import nbformat

# Save the current notebook cleanly
notebook_path = "/content/TextToImageGeneration_CLEAN.ipynb"

with open(notebook_path, "w", encoding="utf-8") as f:
    nbformat.write(nbformat.from_dict({
        "cells": nbformat.reads(open("/content/TextToImageGeneration.ipynb").read(), as_version=4)["cells"],
        "metadata": {},
        "nbformat": 4,
        "nbformat_minor": 0
    }), f)

print("✅ Clean notebook saved:", notebook_path)